services:
  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      - VITE_API_BASE_URL=http://localhost:8083/api/v1
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always
    depends_on:
      - api_gateway
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  # AI Service - Machine Learning Service
  ai_service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    environment:
      - PORT=5000
      - FLASK_ENV=development
      - LOG_LEVEL=INFO
    volumes:
      - ./ai-service:/app
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 1G

  # API Gateway
  api_gateway:
    build:
      context: ./backend
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - "8083:8081"
    env_file:
      - ./.env
    environment:
      - USER_SERVICE_HOST=user_service
      - USER_SERVICE_PORT=9091
      - THREAD_SERVICE_HOST=thread_service
      - THREAD_SERVICE_PORT=9092
      - COMMUNITY_SERVICE_HOST=community_service
      - COMMUNITY_SERVICE_PORT=9093
      - AI_SERVICE_HOST=ai_service
      - AI_SERVICE_PORT=5000
    volumes:
      - ./backend:/app
      - api_gateway_go_mod_cache:/go/pkg/mod
      - api_gateway_go_build_cache:/root/.cache/go-build
    depends_on:
      - user_service
      - thread_service
      - community_service
      - ai_service
    restart: always
    command: >
      sh -c "cd /app/api-gateway && 
             go mod tidy && 
             go mod download && 
             air -c .air.toml"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M

  # User Service - Profile Management
  user_service:
    build:
      context: ./backend
      dockerfile: ./services/user/Dockerfile
    ports:
      - "9091:9091"
    env_file:
      - ./.env
    environment:
      - DATABASE_HOST=user_db
      - DATABASE_PORT=5432
      - DATABASE_URL=postgresql://${USER_DB_USER:-kolin}:${USER_DB_PASSWORD:-kolin}@user_db:5432/${USER_DB_NAME:-user_db}
    volumes:
      - ./backend:/app
      - user_service_go_mod_cache:/go/pkg/mod
      - user_service_go_build_cache:/root/.cache/go-build
    depends_on:
      user_db:
        condition: service_healthy
    restart: always
    command: >
      sh -c "cd /app/services/user && 
             go mod tidy && 
             go mod download && 
             air -c .air.toml"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M

  # Thread Service - Thread Management
  thread_service:
    build:
      context: ./backend
      dockerfile: ./services/thread/Dockerfile
    ports:
      - "9092:9092"
    env_file:
      - ./.env
    environment:
      - DATABASE_HOST=thread_db
      - DATABASE_PORT=5432
      - DATABASE_URL=postgresql://${THREAD_DB_USER:-kolin}:${THREAD_DB_PASSWORD:-kolin}@thread_db:5432/${THREAD_DB_NAME:-thread_db}
      - USER_SERVICE_HOST=user_service
      - USER_SERVICE_PORT=9091
    volumes:
      - ./backend:/app
      - thread_service_go_mod_cache:/go/pkg/mod
      - thread_service_go_build_cache:/root/.cache/go-build
    depends_on:
      thread_db:
        condition: service_healthy
      user_service:
        condition: service_started
    restart: always
    command: >
      sh -c "cd /app/services/thread && 
             go mod tidy && 
             go mod download && 
             air -c .air.toml"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M

  # Event Bus Service
  event_bus:
    build:
      context: ./backend
      dockerfile: event-bus/Dockerfile
    env_file:
      - ./.env
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - USER_SERVICE_HOST=user_service
      - USER_SERVICE_PORT=9091
      - THREAD_SERVICE_HOST=thread_service
      - THREAD_SERVICE_PORT=9092
    volumes:
      - ./backend:/app
      - event_bus_go_mod_cache:/go/pkg/mod
      - event_bus_go_build_cache:/root/.cache/go-build
    depends_on:
      rabbitmq:
        condition: service_healthy
      user_service:
        condition: service_started
      thread_service:
        condition: service_started
    restart: always
    command: >
      sh -c "cd /app/event-bus && 
             go mod tidy && 
             go mod download && 
             air -c .air.toml"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M

  # User Service Database
  user_db:
    image: postgres:14-alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=${USER_DB_USER:-kolin}
      - POSTGRES_PASSWORD=${USER_DB_PASSWORD:-kolin}
      - POSTGRES_DB=${USER_DB_NAME:-user_db}
    volumes:
      - user_db_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_DB_USER:-kolin} -d ${USER_DB_NAME:-user_db}"] # Explicitly check the correct database
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M

  # Thread Service Database
  thread_db:
    image: postgres:14-alpine
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=${THREAD_DB_USER:-kolin}
      - POSTGRES_PASSWORD=${THREAD_DB_PASSWORD:-kolin}
      - POSTGRES_DB=${THREAD_DB_NAME:-thread_db}
    volumes:
      - thread_db_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${THREAD_DB_USER:-kolin} -d ${THREAD_DB_NAME:-thread_db}"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M

  # Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M

  # RabbitMQ for messaging
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    ports:
      - "5672:5672"  # AMQP
      - "15672:15672"  # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M

  # Community Service - Community & Chat Management
  community_service:
    build:
      context: ./backend
      dockerfile: ./services/community/Dockerfile
    ports:
      - "9093:9093"
    environment:
      - DATABASE_HOST=community_db
      - DATABASE_PORT=5432
      - DATABASE_USER=${COMMUNITY_DB_USER:-kolin}
      - DATABASE_PASSWORD=${COMMUNITY_DB_PASSWORD:-kolin}
      - DATABASE_NAME=${COMMUNITY_DB_NAME:-community_db}
      - DATABASE_URL=postgresql://${COMMUNITY_DB_USER:-kolin}:${COMMUNITY_DB_PASSWORD:-kolin}@community_db:5432/${COMMUNITY_DB_NAME:-community_db}
      - COMMUNITY_SERVICE_PORT=9093
      - JWT_SECRET=${JWT_SECRET:-wompwomp123}
      - ENVIRONMENT=${ENVIRONMENT:-development}
    volumes:
      - ./backend:/app
      - community_service_go_mod_cache:/go/pkg/mod
      - community_service_go_build_cache:/root/.cache/go-build
    depends_on:
      community_db:
        condition: service_healthy
    restart: always
    command: >
      sh -c "cd /app/services/community && 
             go mod tidy && 
             go mod download && 
             air -c .air.toml"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M

  # Community Service Database
  community_db:
    image: postgres:14-alpine
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER=${COMMUNITY_DB_USER:-kolin}
      - POSTGRES_PASSWORD=${COMMUNITY_DB_PASSWORD:-kolin}
      - POSTGRES_DB=${COMMUNITY_DB_NAME:-community_db}
    volumes:
      - community_db_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${COMMUNITY_DB_USER:-kolin} -d ${COMMUNITY_DB_NAME:-community_db}"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M

volumes:
  user_db_data:
  thread_db_data:
  community_db_data:
  redis_data:
  rabbitmq_data:
  api_gateway_go_mod_cache:
  api_gateway_go_build_cache:
  user_service_go_mod_cache:
  user_service_go_build_cache:
  thread_service_go_mod_cache:
  thread_service_go_build_cache:
  community_service_go_mod_cache:
  community_service_go_build_cache:
  event_bus_go_mod_cache:
  event_bus_go_build_cache: