services:
  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:${API_GATEWAY_PORT:-8080}/api/v1
      - VITE_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - VITE_RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always
    depends_on:
      - api_gateway
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  # API Gateway
  api_gateway:
    build:
      context: .
      dockerfile: ./backend/api-gateway/Dockerfile
    ports:
      - "${API_GATEWAY_PORT:-8080}:8080"
    environment:
      - USER_SERVICE_HOST=user_service
      - USER_SERVICE_PORT=9091
      - AUTH_SERVICE_HOST=auth_service
      - AUTH_SERVICE_PORT=9090
      - JWT_SECRET=${JWT_SECRET:-wompwomp123}
      - TLS_ENABLED=${TLS_ENABLED:-false}
      - ENVIRONMENT=${ENVIRONMENT:-development}
    depends_on:
      - user_service
      - auth_service
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M

  # User Service - Profile Management
  user_service:
    build:
      context: .
      dockerfile: ./backend/services/user/Dockerfile
    ports:
      - "9091:9091"
    environment:
      - DATABASE_HOST=user_db
      - DATABASE_PORT=5432
      - DATABASE_USER=${USER_DB_USER:-kolin}
      - DATABASE_PASSWORD=${USER_DB_PASSWORD:-kolin}
      - DATABASE_NAME=${USER_DB_NAME:-user_db}
      - DATABASE_URL=postgresql://${USER_DB_USER:-kolin}:${USER_DB_PASSWORD:-kolin}@user_db:5432/${USER_DB_NAME:-user_db}
      - AUTH_SERVICE_HOST=auth_service
      - AUTH_SERVICE_PORT=9090
      - JWT_SECRET=${JWT_SECRET:-wompwomp123}
      - ENVIRONMENT=${ENVIRONMENT:-development}
    depends_on:
      user_db:
        condition: service_healthy
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M

  # Auth Service - Authentication & Authorization
  auth_service:
    build:
      context: .
      dockerfile: ./backend/services/auth/Dockerfile
    ports:
      - "9090:9090"
    environment:
      - DATABASE_HOST=auth_db
      - DATABASE_PORT=5432
      - DATABASE_USER=${AUTH_DB_USER:-kolin}
      - DATABASE_PASSWORD=${AUTH_DB_PASSWORD:-kolin}
      - DATABASE_NAME=${AUTH_DB_NAME:-auth_db}
      - DATABASE_URL=postgresql://${AUTH_DB_USER:-kolin}:${AUTH_DB_PASSWORD:-kolin}@auth_db:5432/${AUTH_DB_NAME:-auth_db}
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - REDIS_URL=redis://redis:6379/0
      - USER_SERVICE_HOST=user_service
      - USER_SERVICE_PORT=9091
      - JWT_SECRET=${JWT_SECRET:-wompwomp123}
      - JWT_EXPIRY=${JWT_EXPIRY:-3600}
      - REFRESH_TOKEN_EXPIRY=${REFRESH_TOKEN_EXPIRY:-604800}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
      - ENVIRONMENT=${ENVIRONMENT:-development}
    depends_on:
      auth_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M

  # Event Bus Service
  event_bus:
    build:
      context: .
      dockerfile: ./backend/event-bus/Dockerfile
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - USER_SERVICE_HOST=user_service
      - USER_SERVICE_PORT=9091
      - AUTH_SERVICE_HOST=auth_service
      - AUTH_SERVICE_PORT=9090
      - ENVIRONMENT=${ENVIRONMENT:-development}
    depends_on:
      rabbitmq:
        condition: service_healthy
      user_service:
        condition: service_started
      auth_service:
        condition: service_started
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M

  # Auth Service Database
  auth_db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${AUTH_DB_USER:-kolin}
      - POSTGRES_PASSWORD=${AUTH_DB_PASSWORD:-kolin}
      - POSTGRES_DB=${AUTH_DB_NAME:-auth_db}
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_DB_USER:-kolin}"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M

  # User Service Database
  user_db:
    image: postgres:14-alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=${USER_DB_USER:-kolin}
      - POSTGRES_PASSWORD=${USER_DB_PASSWORD:-kolin}
      - POSTGRES_DB=${USER_DB_NAME:-user_db}
    volumes:
      - user_db_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_DB_USER:-kolin}"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M

  # Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M

  # RabbitMQ for messaging
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    ports:
      - "5672:5672"  # AMQP
      - "15672:15672"  # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M

volumes:
  auth_db_data:
  user_db_data:
  redis_data:
  rabbitmq_data: