# Hot reloading configuration for Python Flask applications

root = "."
tmp_dir = "tmp"

[build]
cmd = "python app.py"
bin = ""
include_ext = ["py"]
exclude_dir = ["__pycache__", "tmp", "venv", ".venv"]
include_dir = []
exclude_file = []
delay = 1000 # ms
stop_on_error = true
log = "air_errors.log"

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true 