// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: proto/thread.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Media information
type MediaInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // Image, GIF, Video
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaInfo) Reset() {
	*x = MediaInfo{}
	mi := &file_proto_thread_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaInfo) ProtoMessage() {}

func (x *MediaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaInfo.ProtoReflect.Descriptor instead.
func (*MediaInfo) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{0}
}

func (x *MediaInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MediaInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Create Thread
type CreateThreadRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content          string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	WhoCanReply      string                 `protobuf:"bytes,3,opt,name=who_can_reply,json=whoCanReply,proto3" json:"who_can_reply,omitempty"` // Everyone, Accounts You Follow, Verified Accounts
	CategoryNames    []string               `protobuf:"bytes,4,rep,name=category_names,json=categoryNames,proto3" json:"category_names,omitempty"`
	Hashtags         []string               `protobuf:"bytes,5,rep,name=hashtags,proto3" json:"hashtags,omitempty"`
	MentionedUserIds []string               `protobuf:"bytes,6,rep,name=mentioned_user_ids,json=mentionedUserIds,proto3" json:"mentioned_user_ids,omitempty"`
	Media            []*MediaInfo           `protobuf:"bytes,7,rep,name=media,proto3" json:"media,omitempty"`
	ScheduledAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	CommunityId      string                 `protobuf:"bytes,9,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	IsAdvertisement  bool                   `protobuf:"varint,10,opt,name=is_advertisement,json=isAdvertisement,proto3" json:"is_advertisement,omitempty"`
	// For poll
	Poll          *PollInfo `protobuf:"bytes,11,opt,name=poll,proto3" json:"poll,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateThreadRequest) Reset() {
	*x = CreateThreadRequest{}
	mi := &file_proto_thread_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateThreadRequest) ProtoMessage() {}

func (x *CreateThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateThreadRequest.ProtoReflect.Descriptor instead.
func (*CreateThreadRequest) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{1}
}

func (x *CreateThreadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateThreadRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateThreadRequest) GetWhoCanReply() string {
	if x != nil {
		return x.WhoCanReply
	}
	return ""
}

func (x *CreateThreadRequest) GetCategoryNames() []string {
	if x != nil {
		return x.CategoryNames
	}
	return nil
}

func (x *CreateThreadRequest) GetHashtags() []string {
	if x != nil {
		return x.Hashtags
	}
	return nil
}

func (x *CreateThreadRequest) GetMentionedUserIds() []string {
	if x != nil {
		return x.MentionedUserIds
	}
	return nil
}

func (x *CreateThreadRequest) GetMedia() []*MediaInfo {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *CreateThreadRequest) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *CreateThreadRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

func (x *CreateThreadRequest) GetIsAdvertisement() bool {
	if x != nil {
		return x.IsAdvertisement
	}
	return false
}

func (x *CreateThreadRequest) GetPoll() *PollInfo {
	if x != nil {
		return x.Poll
	}
	return nil
}

type PollInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Options       []string               `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	ClosesAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=closes_at,json=closesAt,proto3" json:"closes_at,omitempty"`
	WhoCanVote    string                 `protobuf:"bytes,4,opt,name=who_can_vote,json=whoCanVote,proto3" json:"who_can_vote,omitempty"` // Everyone, Accounts You Follow, Verified Accounts
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollInfo) Reset() {
	*x = PollInfo{}
	mi := &file_proto_thread_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollInfo) ProtoMessage() {}

func (x *PollInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollInfo.ProtoReflect.Descriptor instead.
func (*PollInfo) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{2}
}

func (x *PollInfo) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *PollInfo) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *PollInfo) GetClosesAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClosesAt
	}
	return nil
}

func (x *PollInfo) GetWhoCanVote() string {
	if x != nil {
		return x.WhoCanVote
	}
	return ""
}

// Get Thread
type GetThreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThreadRequest) Reset() {
	*x = GetThreadRequest{}
	mi := &file_proto_thread_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThreadRequest) ProtoMessage() {}

func (x *GetThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThreadRequest.ProtoReflect.Descriptor instead.
func (*GetThreadRequest) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{3}
}

func (x *GetThreadRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

// Get Threads by User
type GetThreadsByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThreadsByUserRequest) Reset() {
	*x = GetThreadsByUserRequest{}
	mi := &file_proto_thread_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThreadsByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThreadsByUserRequest) ProtoMessage() {}

func (x *GetThreadsByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThreadsByUserRequest.ProtoReflect.Descriptor instead.
func (*GetThreadsByUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{4}
}

func (x *GetThreadsByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetThreadsByUserRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetThreadsByUserRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Update Thread
type UpdateThreadRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ThreadId            string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	Content             string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	IsPinned            bool                   `protobuf:"varint,3,opt,name=is_pinned,json=isPinned,proto3" json:"is_pinned,omitempty"`
	AddCategoryNames    []string               `protobuf:"bytes,4,rep,name=add_category_names,json=addCategoryNames,proto3" json:"add_category_names,omitempty"`
	RemoveCategoryNames []string               `protobuf:"bytes,5,rep,name=remove_category_names,json=removeCategoryNames,proto3" json:"remove_category_names,omitempty"`
	AddHashtags         []string               `protobuf:"bytes,6,rep,name=add_hashtags,json=addHashtags,proto3" json:"add_hashtags,omitempty"`
	RemoveHashtags      []string               `protobuf:"bytes,7,rep,name=remove_hashtags,json=removeHashtags,proto3" json:"remove_hashtags,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateThreadRequest) Reset() {
	*x = UpdateThreadRequest{}
	mi := &file_proto_thread_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateThreadRequest) ProtoMessage() {}

func (x *UpdateThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateThreadRequest.ProtoReflect.Descriptor instead.
func (*UpdateThreadRequest) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateThreadRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *UpdateThreadRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateThreadRequest) GetIsPinned() bool {
	if x != nil {
		return x.IsPinned
	}
	return false
}

func (x *UpdateThreadRequest) GetAddCategoryNames() []string {
	if x != nil {
		return x.AddCategoryNames
	}
	return nil
}

func (x *UpdateThreadRequest) GetRemoveCategoryNames() []string {
	if x != nil {
		return x.RemoveCategoryNames
	}
	return nil
}

func (x *UpdateThreadRequest) GetAddHashtags() []string {
	if x != nil {
		return x.AddHashtags
	}
	return nil
}

func (x *UpdateThreadRequest) GetRemoveHashtags() []string {
	if x != nil {
		return x.RemoveHashtags
	}
	return nil
}

// Delete Thread
type DeleteThreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // For authorization check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteThreadRequest) Reset() {
	*x = DeleteThreadRequest{}
	mi := &file_proto_thread_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteThreadRequest) ProtoMessage() {}

func (x *DeleteThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteThreadRequest.ProtoReflect.Descriptor instead.
func (*DeleteThreadRequest) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteThreadRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *DeleteThreadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Create Reply
type CreateReplyRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ThreadId         string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content          string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ParentReplyId    string                 `protobuf:"bytes,4,opt,name=parent_reply_id,json=parentReplyId,proto3" json:"parent_reply_id,omitempty"`
	Media            []*MediaInfo           `protobuf:"bytes,5,rep,name=media,proto3" json:"media,omitempty"`
	MentionedUserIds []string               `protobuf:"bytes,6,rep,name=mentioned_user_ids,json=mentionedUserIds,proto3" json:"mentioned_user_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateReplyRequest) Reset() {
	*x = CreateReplyRequest{}
	mi := &file_proto_thread_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReplyRequest) ProtoMessage() {}

func (x *CreateReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReplyRequest.ProtoReflect.Descriptor instead.
func (*CreateReplyRequest) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{7}
}

func (x *CreateReplyRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *CreateReplyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateReplyRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateReplyRequest) GetParentReplyId() string {
	if x != nil {
		return x.ParentReplyId
	}
	return ""
}

func (x *CreateReplyRequest) GetMedia() []*MediaInfo {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *CreateReplyRequest) GetMentionedUserIds() []string {
	if x != nil {
		return x.MentionedUserIds
	}
	return nil
}

// Get Replies
type GetRepliesByThreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	ParentReplyId string                 `protobuf:"bytes,2,opt,name=parent_reply_id,json=parentReplyId,proto3" json:"parent_reply_id,omitempty"` // Optional, if provided gets replies to a specific reply
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepliesByThreadRequest) Reset() {
	*x = GetRepliesByThreadRequest{}
	mi := &file_proto_thread_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepliesByThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepliesByThreadRequest) ProtoMessage() {}

func (x *GetRepliesByThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepliesByThreadRequest.ProtoReflect.Descriptor instead.
func (*GetRepliesByThreadRequest) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{8}
}

func (x *GetRepliesByThreadRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *GetRepliesByThreadRequest) GetParentReplyId() string {
	if x != nil {
		return x.ParentReplyId
	}
	return ""
}

func (x *GetRepliesByThreadRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetRepliesByThreadRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Update Reply
type UpdateReplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyId       string                 `protobuf:"bytes,1,opt,name=reply_id,json=replyId,proto3" json:"reply_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // For authorization check
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	IsPinned      bool                   `protobuf:"varint,4,opt,name=is_pinned,json=isPinned,proto3" json:"is_pinned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReplyRequest) Reset() {
	*x = UpdateReplyRequest{}
	mi := &file_proto_thread_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReplyRequest) ProtoMessage() {}

func (x *UpdateReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReplyRequest.ProtoReflect.Descriptor instead.
func (*UpdateReplyRequest) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateReplyRequest) GetReplyId() string {
	if x != nil {
		return x.ReplyId
	}
	return ""
}

func (x *UpdateReplyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateReplyRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateReplyRequest) GetIsPinned() bool {
	if x != nil {
		return x.IsPinned
	}
	return false
}

// Delete Reply
type DeleteReplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyId       string                 `protobuf:"bytes,1,opt,name=reply_id,json=replyId,proto3" json:"reply_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // For authorization check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReplyRequest) Reset() {
	*x = DeleteReplyRequest{}
	mi := &file_proto_thread_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReplyRequest) ProtoMessage() {}

func (x *DeleteReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReplyRequest.ProtoReflect.Descriptor instead.
func (*DeleteReplyRequest) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteReplyRequest) GetReplyId() string {
	if x != nil {
		return x.ReplyId
	}
	return ""
}

func (x *DeleteReplyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Like Thread
type LikeThreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeThreadRequest) Reset() {
	*x = LikeThreadRequest{}
	mi := &file_proto_thread_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeThreadRequest) ProtoMessage() {}

func (x *LikeThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeThreadRequest.ProtoReflect.Descriptor instead.
func (*LikeThreadRequest) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{11}
}

func (x *LikeThreadRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *LikeThreadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Unlike Thread
type UnlikeThreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeThreadRequest) Reset() {
	*x = UnlikeThreadRequest{}
	mi := &file_proto_thread_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeThreadRequest) ProtoMessage() {}

func (x *UnlikeThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeThreadRequest.ProtoReflect.Descriptor instead.
func (*UnlikeThreadRequest) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{12}
}

func (x *UnlikeThreadRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *UnlikeThreadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Like Reply
type LikeReplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyId       string                 `protobuf:"bytes,1,opt,name=reply_id,json=replyId,proto3" json:"reply_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeReplyRequest) Reset() {
	*x = LikeReplyRequest{}
	mi := &file_proto_thread_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeReplyRequest) ProtoMessage() {}

func (x *LikeReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeReplyRequest.ProtoReflect.Descriptor instead.
func (*LikeReplyRequest) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{13}
}

func (x *LikeReplyRequest) GetReplyId() string {
	if x != nil {
		return x.ReplyId
	}
	return ""
}

func (x *LikeReplyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Unlike Reply
type UnlikeReplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyId       string                 `protobuf:"bytes,1,opt,name=reply_id,json=replyId,proto3" json:"reply_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeReplyRequest) Reset() {
	*x = UnlikeReplyRequest{}
	mi := &file_proto_thread_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeReplyRequest) ProtoMessage() {}

func (x *UnlikeReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeReplyRequest.ProtoReflect.Descriptor instead.
func (*UnlikeReplyRequest) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{14}
}

func (x *UnlikeReplyRequest) GetReplyId() string {
	if x != nil {
		return x.ReplyId
	}
	return ""
}

func (x *UnlikeReplyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Repost Thread
type RepostThreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RepostText    string                 `protobuf:"bytes,3,opt,name=repost_text,json=repostText,proto3" json:"repost_text,omitempty"` // Optional text to add to the repost
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepostThreadRequest) Reset() {
	*x = RepostThreadRequest{}
	mi := &file_proto_thread_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepostThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepostThreadRequest) ProtoMessage() {}

func (x *RepostThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepostThreadRequest.ProtoReflect.Descriptor instead.
func (*RepostThreadRequest) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{15}
}

func (x *RepostThreadRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *RepostThreadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RepostThreadRequest) GetRepostText() string {
	if x != nil {
		return x.RepostText
	}
	return ""
}

// Remove Repost
type RemoveRepostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRepostRequest) Reset() {
	*x = RemoveRepostRequest{}
	mi := &file_proto_thread_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRepostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRepostRequest) ProtoMessage() {}

func (x *RemoveRepostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRepostRequest.ProtoReflect.Descriptor instead.
func (*RemoveRepostRequest) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{16}
}

func (x *RemoveRepostRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *RemoveRepostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Bookmark Thread
type BookmarkThreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookmarkThreadRequest) Reset() {
	*x = BookmarkThreadRequest{}
	mi := &file_proto_thread_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookmarkThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookmarkThreadRequest) ProtoMessage() {}

func (x *BookmarkThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookmarkThreadRequest.ProtoReflect.Descriptor instead.
func (*BookmarkThreadRequest) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{17}
}

func (x *BookmarkThreadRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *BookmarkThreadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Remove Bookmark
type RemoveBookmarkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBookmarkRequest) Reset() {
	*x = RemoveBookmarkRequest{}
	mi := &file_proto_thread_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBookmarkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBookmarkRequest) ProtoMessage() {}

func (x *RemoveBookmarkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBookmarkRequest.ProtoReflect.Descriptor instead.
func (*RemoveBookmarkRequest) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{18}
}

func (x *RemoveBookmarkRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *RemoveBookmarkRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Create Poll Vote
type VotePollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollId        string                 `protobuf:"bytes,1,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	OptionId      string                 `protobuf:"bytes,2,opt,name=option_id,json=optionId,proto3" json:"option_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VotePollRequest) Reset() {
	*x = VotePollRequest{}
	mi := &file_proto_thread_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VotePollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VotePollRequest) ProtoMessage() {}

func (x *VotePollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VotePollRequest.ProtoReflect.Descriptor instead.
func (*VotePollRequest) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{19}
}

func (x *VotePollRequest) GetPollId() string {
	if x != nil {
		return x.PollId
	}
	return ""
}

func (x *VotePollRequest) GetOptionId() string {
	if x != nil {
		return x.OptionId
	}
	return ""
}

func (x *VotePollRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Get Poll Results
type GetPollResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollId        string                 `protobuf:"bytes,1,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPollResultsRequest) Reset() {
	*x = GetPollResultsRequest{}
	mi := &file_proto_thread_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPollResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPollResultsRequest) ProtoMessage() {}

func (x *GetPollResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPollResultsRequest.ProtoReflect.Descriptor instead.
func (*GetPollResultsRequest) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{20}
}

func (x *GetPollResultsRequest) GetPollId() string {
	if x != nil {
		return x.PollId
	}
	return ""
}

// Thread Response
type ThreadResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ThreadId        string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content         string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	IsPinned        bool                   `protobuf:"varint,4,opt,name=is_pinned,json=isPinned,proto3" json:"is_pinned,omitempty"`
	WhoCanReply     string                 `protobuf:"bytes,5,opt,name=who_can_reply,json=whoCanReply,proto3" json:"who_can_reply,omitempty"`
	ScheduledAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	CommunityId     string                 `protobuf:"bytes,7,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	IsAdvertisement bool                   `protobuf:"varint,8,opt,name=is_advertisement,json=isAdvertisement,proto3" json:"is_advertisement,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Stats
	ReplyCount  int32 `protobuf:"varint,11,opt,name=reply_count,json=replyCount,proto3" json:"reply_count,omitempty"`
	LikeCount   int32 `protobuf:"varint,12,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	RepostCount int32 `protobuf:"varint,13,opt,name=repost_count,json=repostCount,proto3" json:"repost_count,omitempty"`
	ViewCount   int32 `protobuf:"varint,14,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	// Related data
	Media            []*MediaResponse `protobuf:"bytes,15,rep,name=media,proto3" json:"media,omitempty"`
	Hashtags         []string         `protobuf:"bytes,16,rep,name=hashtags,proto3" json:"hashtags,omitempty"`
	Categories       []string         `protobuf:"bytes,17,rep,name=categories,proto3" json:"categories,omitempty"`
	MentionedUserIds []string         `protobuf:"bytes,18,rep,name=mentioned_user_ids,json=mentionedUserIds,proto3" json:"mentioned_user_ids,omitempty"`
	Poll             *PollResponse    `protobuf:"bytes,19,opt,name=poll,proto3" json:"poll,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ThreadResponse) Reset() {
	*x = ThreadResponse{}
	mi := &file_proto_thread_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadResponse) ProtoMessage() {}

func (x *ThreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadResponse.ProtoReflect.Descriptor instead.
func (*ThreadResponse) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{21}
}

func (x *ThreadResponse) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *ThreadResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ThreadResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ThreadResponse) GetIsPinned() bool {
	if x != nil {
		return x.IsPinned
	}
	return false
}

func (x *ThreadResponse) GetWhoCanReply() string {
	if x != nil {
		return x.WhoCanReply
	}
	return ""
}

func (x *ThreadResponse) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *ThreadResponse) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

func (x *ThreadResponse) GetIsAdvertisement() bool {
	if x != nil {
		return x.IsAdvertisement
	}
	return false
}

func (x *ThreadResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ThreadResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ThreadResponse) GetReplyCount() int32 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

func (x *ThreadResponse) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *ThreadResponse) GetRepostCount() int32 {
	if x != nil {
		return x.RepostCount
	}
	return 0
}

func (x *ThreadResponse) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *ThreadResponse) GetMedia() []*MediaResponse {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *ThreadResponse) GetHashtags() []string {
	if x != nil {
		return x.Hashtags
	}
	return nil
}

func (x *ThreadResponse) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *ThreadResponse) GetMentionedUserIds() []string {
	if x != nil {
		return x.MentionedUserIds
	}
	return nil
}

func (x *ThreadResponse) GetPoll() *PollResponse {
	if x != nil {
		return x.Poll
	}
	return nil
}

// Media Response
type MediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaResponse) Reset() {
	*x = MediaResponse{}
	mi := &file_proto_thread_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaResponse) ProtoMessage() {}

func (x *MediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaResponse.ProtoReflect.Descriptor instead.
func (*MediaResponse) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{22}
}

func (x *MediaResponse) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *MediaResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MediaResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Poll Response
type PollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollId        string                 `protobuf:"bytes,1,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	ThreadId      string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	Question      string                 `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	ClosesAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=closes_at,json=closesAt,proto3" json:"closes_at,omitempty"`
	WhoCanVote    string                 `protobuf:"bytes,5,opt,name=who_can_vote,json=whoCanVote,proto3" json:"who_can_vote,omitempty"`
	Options       []*PollOptionResponse  `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty"`
	TotalVotes    int32                  `protobuf:"varint,7,opt,name=total_votes,json=totalVotes,proto3" json:"total_votes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollResponse) Reset() {
	*x = PollResponse{}
	mi := &file_proto_thread_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollResponse) ProtoMessage() {}

func (x *PollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollResponse.ProtoReflect.Descriptor instead.
func (*PollResponse) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{23}
}

func (x *PollResponse) GetPollId() string {
	if x != nil {
		return x.PollId
	}
	return ""
}

func (x *PollResponse) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *PollResponse) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *PollResponse) GetClosesAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClosesAt
	}
	return nil
}

func (x *PollResponse) GetWhoCanVote() string {
	if x != nil {
		return x.WhoCanVote
	}
	return ""
}

func (x *PollResponse) GetOptions() []*PollOptionResponse {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *PollResponse) GetTotalVotes() int32 {
	if x != nil {
		return x.TotalVotes
	}
	return 0
}

// Poll Option Response
type PollOptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OptionId      string                 `protobuf:"bytes,1,opt,name=option_id,json=optionId,proto3" json:"option_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	VoteCount     int32                  `protobuf:"varint,3,opt,name=vote_count,json=voteCount,proto3" json:"vote_count,omitempty"`
	Percentage    float32                `protobuf:"fixed32,4,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollOptionResponse) Reset() {
	*x = PollOptionResponse{}
	mi := &file_proto_thread_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollOptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollOptionResponse) ProtoMessage() {}

func (x *PollOptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollOptionResponse.ProtoReflect.Descriptor instead.
func (*PollOptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{24}
}

func (x *PollOptionResponse) GetOptionId() string {
	if x != nil {
		return x.OptionId
	}
	return ""
}

func (x *PollOptionResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PollOptionResponse) GetVoteCount() int32 {
	if x != nil {
		return x.VoteCount
	}
	return 0
}

func (x *PollOptionResponse) GetPercentage() float32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

// Poll Results Response
type PollResultsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PollId            string                 `protobuf:"bytes,1,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	Options           []*PollOptionResponse  `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	TotalVotes        int32                  `protobuf:"varint,3,opt,name=total_votes,json=totalVotes,proto3" json:"total_votes,omitempty"`
	HasUserVoted      bool                   `protobuf:"varint,4,opt,name=has_user_voted,json=hasUserVoted,proto3" json:"has_user_voted,omitempty"`
	UserVotedOptionId string                 `protobuf:"bytes,5,opt,name=user_voted_option_id,json=userVotedOptionId,proto3" json:"user_voted_option_id,omitempty"`
	IsClosed          bool                   `protobuf:"varint,6,opt,name=is_closed,json=isClosed,proto3" json:"is_closed,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PollResultsResponse) Reset() {
	*x = PollResultsResponse{}
	mi := &file_proto_thread_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollResultsResponse) ProtoMessage() {}

func (x *PollResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollResultsResponse.ProtoReflect.Descriptor instead.
func (*PollResultsResponse) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{25}
}

func (x *PollResultsResponse) GetPollId() string {
	if x != nil {
		return x.PollId
	}
	return ""
}

func (x *PollResultsResponse) GetOptions() []*PollOptionResponse {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *PollResultsResponse) GetTotalVotes() int32 {
	if x != nil {
		return x.TotalVotes
	}
	return 0
}

func (x *PollResultsResponse) GetHasUserVoted() bool {
	if x != nil {
		return x.HasUserVoted
	}
	return false
}

func (x *PollResultsResponse) GetUserVotedOptionId() string {
	if x != nil {
		return x.UserVotedOptionId
	}
	return ""
}

func (x *PollResultsResponse) GetIsClosed() bool {
	if x != nil {
		return x.IsClosed
	}
	return false
}

// Reply Response
type ReplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyId       string                 `protobuf:"bytes,1,opt,name=reply_id,json=replyId,proto3" json:"reply_id,omitempty"`
	ThreadId      string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	IsPinned      bool                   `protobuf:"varint,5,opt,name=is_pinned,json=isPinned,proto3" json:"is_pinned,omitempty"`
	ParentReplyId string                 `protobuf:"bytes,6,opt,name=parent_reply_id,json=parentReplyId,proto3" json:"parent_reply_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Stats
	LikeCount  int32 `protobuf:"varint,9,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	ReplyCount int32 `protobuf:"varint,10,opt,name=reply_count,json=replyCount,proto3" json:"reply_count,omitempty"`
	// Related data
	Media            []*MediaResponse `protobuf:"bytes,11,rep,name=media,proto3" json:"media,omitempty"`
	MentionedUserIds []string         `protobuf:"bytes,12,rep,name=mentioned_user_ids,json=mentionedUserIds,proto3" json:"mentioned_user_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReplyResponse) Reset() {
	*x = ReplyResponse{}
	mi := &file_proto_thread_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyResponse) ProtoMessage() {}

func (x *ReplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyResponse.ProtoReflect.Descriptor instead.
func (*ReplyResponse) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{26}
}

func (x *ReplyResponse) GetReplyId() string {
	if x != nil {
		return x.ReplyId
	}
	return ""
}

func (x *ReplyResponse) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *ReplyResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReplyResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReplyResponse) GetIsPinned() bool {
	if x != nil {
		return x.IsPinned
	}
	return false
}

func (x *ReplyResponse) GetParentReplyId() string {
	if x != nil {
		return x.ParentReplyId
	}
	return ""
}

func (x *ReplyResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ReplyResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ReplyResponse) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *ReplyResponse) GetReplyCount() int32 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

func (x *ReplyResponse) GetMedia() []*MediaResponse {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *ReplyResponse) GetMentionedUserIds() []string {
	if x != nil {
		return x.MentionedUserIds
	}
	return nil
}

// Multiple Threads Response
type ThreadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Threads       []*ThreadResponse      `protobuf:"bytes,1,rep,name=threads,proto3" json:"threads,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadsResponse) Reset() {
	*x = ThreadsResponse{}
	mi := &file_proto_thread_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadsResponse) ProtoMessage() {}

func (x *ThreadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadsResponse.ProtoReflect.Descriptor instead.
func (*ThreadsResponse) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{27}
}

func (x *ThreadsResponse) GetThreads() []*ThreadResponse {
	if x != nil {
		return x.Threads
	}
	return nil
}

func (x *ThreadsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ThreadsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ThreadsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Multiple Replies Response
type RepliesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replies       []*ReplyResponse       `protobuf:"bytes,1,rep,name=replies,proto3" json:"replies,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepliesResponse) Reset() {
	*x = RepliesResponse{}
	mi := &file_proto_thread_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepliesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepliesResponse) ProtoMessage() {}

func (x *RepliesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepliesResponse.ProtoReflect.Descriptor instead.
func (*RepliesResponse) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{28}
}

func (x *RepliesResponse) GetReplies() []*ReplyResponse {
	if x != nil {
		return x.Replies
	}
	return nil
}

func (x *RepliesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *RepliesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *RepliesResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CreatePollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	Question      string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	Options       []string               `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	ClosesAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=closes_at,json=closesAt,proto3" json:"closes_at,omitempty"`
	WhoCanVote    string                 `protobuf:"bytes,5,opt,name=who_can_vote,json=whoCanVote,proto3" json:"who_can_vote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePollRequest) Reset() {
	*x = CreatePollRequest{}
	mi := &file_proto_thread_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePollRequest) ProtoMessage() {}

func (x *CreatePollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePollRequest.ProtoReflect.Descriptor instead.
func (*CreatePollRequest) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{29}
}

func (x *CreatePollRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *CreatePollRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *CreatePollRequest) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *CreatePollRequest) GetClosesAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClosesAt
	}
	return nil
}

func (x *CreatePollRequest) GetWhoCanVote() string {
	if x != nil {
		return x.WhoCanVote
	}
	return ""
}

var File_proto_thread_proto protoreflect.FileDescriptor

const file_proto_thread_proto_rawDesc = "" +
	"\n" +
	"\x12proto/thread.proto\x12\x06thread\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"1\n" +
	"\tMediaInfo\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"\xb9\x03\n" +
	"\x13CreateThreadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\"\n" +
	"\rwho_can_reply\x18\x03 \x01(\tR\vwhoCanReply\x12%\n" +
	"\x0ecategory_names\x18\x04 \x03(\tR\rcategoryNames\x12\x1a\n" +
	"\bhashtags\x18\x05 \x03(\tR\bhashtags\x12,\n" +
	"\x12mentioned_user_ids\x18\x06 \x03(\tR\x10mentionedUserIds\x12'\n" +
	"\x05media\x18\a \x03(\v2\x11.thread.MediaInfoR\x05media\x12=\n" +
	"\fscheduled_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x12!\n" +
	"\fcommunity_id\x18\t \x01(\tR\vcommunityId\x12)\n" +
	"\x10is_advertisement\x18\n" +
	" \x01(\bR\x0fisAdvertisement\x12$\n" +
	"\x04poll\x18\v \x01(\v2\x10.thread.PollInfoR\x04poll\"\x9b\x01\n" +
	"\bPollInfo\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12\x18\n" +
	"\aoptions\x18\x02 \x03(\tR\aoptions\x127\n" +
	"\tcloses_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bclosesAt\x12 \n" +
	"\fwho_can_vote\x18\x04 \x01(\tR\n" +
	"whoCanVote\"/\n" +
	"\x10GetThreadRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\"\\\n" +
	"\x17GetThreadsByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x97\x02\n" +
	"\x13UpdateThreadRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1b\n" +
	"\tis_pinned\x18\x03 \x01(\bR\bisPinned\x12,\n" +
	"\x12add_category_names\x18\x04 \x03(\tR\x10addCategoryNames\x122\n" +
	"\x15remove_category_names\x18\x05 \x03(\tR\x13removeCategoryNames\x12!\n" +
	"\fadd_hashtags\x18\x06 \x03(\tR\vaddHashtags\x12'\n" +
	"\x0fremove_hashtags\x18\a \x03(\tR\x0eremoveHashtags\"K\n" +
	"\x13DeleteThreadRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xe3\x01\n" +
	"\x12CreateReplyRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12&\n" +
	"\x0fparent_reply_id\x18\x04 \x01(\tR\rparentReplyId\x12'\n" +
	"\x05media\x18\x05 \x03(\v2\x11.thread.MediaInfoR\x05media\x12,\n" +
	"\x12mentioned_user_ids\x18\x06 \x03(\tR\x10mentionedUserIds\"\x8a\x01\n" +
	"\x19GetRepliesByThreadRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12&\n" +
	"\x0fparent_reply_id\x18\x02 \x01(\tR\rparentReplyId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x7f\n" +
	"\x12UpdateReplyRequest\x12\x19\n" +
	"\breply_id\x18\x01 \x01(\tR\areplyId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\tis_pinned\x18\x04 \x01(\bR\bisPinned\"H\n" +
	"\x12DeleteReplyRequest\x12\x19\n" +
	"\breply_id\x18\x01 \x01(\tR\areplyId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"I\n" +
	"\x11LikeThreadRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"K\n" +
	"\x13UnlikeThreadRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"F\n" +
	"\x10LikeReplyRequest\x12\x19\n" +
	"\breply_id\x18\x01 \x01(\tR\areplyId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"H\n" +
	"\x12UnlikeReplyRequest\x12\x19\n" +
	"\breply_id\x18\x01 \x01(\tR\areplyId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"l\n" +
	"\x13RepostThreadRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vrepost_text\x18\x03 \x01(\tR\n" +
	"repostText\"K\n" +
	"\x13RemoveRepostRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"M\n" +
	"\x15BookmarkThreadRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"M\n" +
	"\x15RemoveBookmarkRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"`\n" +
	"\x0fVotePollRequest\x12\x17\n" +
	"\apoll_id\x18\x01 \x01(\tR\x06pollId\x12\x1b\n" +
	"\toption_id\x18\x02 \x01(\tR\boptionId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"0\n" +
	"\x15GetPollResultsRequest\x12\x17\n" +
	"\apoll_id\x18\x01 \x01(\tR\x06pollId\"\xe7\x05\n" +
	"\x0eThreadResponse\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\tis_pinned\x18\x04 \x01(\bR\bisPinned\x12\"\n" +
	"\rwho_can_reply\x18\x05 \x01(\tR\vwhoCanReply\x12=\n" +
	"\fscheduled_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x12!\n" +
	"\fcommunity_id\x18\a \x01(\tR\vcommunityId\x12)\n" +
	"\x10is_advertisement\x18\b \x01(\bR\x0fisAdvertisement\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vreply_count\x18\v \x01(\x05R\n" +
	"replyCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\f \x01(\x05R\tlikeCount\x12!\n" +
	"\frepost_count\x18\r \x01(\x05R\vrepostCount\x12\x1d\n" +
	"\n" +
	"view_count\x18\x0e \x01(\x05R\tviewCount\x12+\n" +
	"\x05media\x18\x0f \x03(\v2\x15.thread.MediaResponseR\x05media\x12\x1a\n" +
	"\bhashtags\x18\x10 \x03(\tR\bhashtags\x12\x1e\n" +
	"\n" +
	"categories\x18\x11 \x03(\tR\n" +
	"categories\x12,\n" +
	"\x12mentioned_user_ids\x18\x12 \x03(\tR\x10mentionedUserIds\x12(\n" +
	"\x04poll\x18\x13 \x01(\v2\x14.thread.PollResponseR\x04poll\"P\n" +
	"\rMediaResponse\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"\x92\x02\n" +
	"\fPollResponse\x12\x17\n" +
	"\apoll_id\x18\x01 \x01(\tR\x06pollId\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\x12\x1a\n" +
	"\bquestion\x18\x03 \x01(\tR\bquestion\x127\n" +
	"\tcloses_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bclosesAt\x12 \n" +
	"\fwho_can_vote\x18\x05 \x01(\tR\n" +
	"whoCanVote\x124\n" +
	"\aoptions\x18\x06 \x03(\v2\x1a.thread.PollOptionResponseR\aoptions\x12\x1f\n" +
	"\vtotal_votes\x18\a \x01(\x05R\n" +
	"totalVotes\"\x84\x01\n" +
	"\x12PollOptionResponse\x12\x1b\n" +
	"\toption_id\x18\x01 \x01(\tR\boptionId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"vote_count\x18\x03 \x01(\x05R\tvoteCount\x12\x1e\n" +
	"\n" +
	"percentage\x18\x04 \x01(\x02R\n" +
	"percentage\"\xf9\x01\n" +
	"\x13PollResultsResponse\x12\x17\n" +
	"\apoll_id\x18\x01 \x01(\tR\x06pollId\x124\n" +
	"\aoptions\x18\x02 \x03(\v2\x1a.thread.PollOptionResponseR\aoptions\x12\x1f\n" +
	"\vtotal_votes\x18\x03 \x01(\x05R\n" +
	"totalVotes\x12$\n" +
	"\x0ehas_user_voted\x18\x04 \x01(\bR\fhasUserVoted\x12/\n" +
	"\x14user_voted_option_id\x18\x05 \x01(\tR\x11userVotedOptionId\x12\x1b\n" +
	"\tis_closed\x18\x06 \x01(\bR\bisClosed\"\xd0\x03\n" +
	"\rReplyResponse\x12\x19\n" +
	"\breply_id\x18\x01 \x01(\tR\areplyId\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1b\n" +
	"\tis_pinned\x18\x05 \x01(\bR\bisPinned\x12&\n" +
	"\x0fparent_reply_id\x18\x06 \x01(\tR\rparentReplyId\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"like_count\x18\t \x01(\x05R\tlikeCount\x12\x1f\n" +
	"\vreply_count\x18\n" +
	" \x01(\x05R\n" +
	"replyCount\x12+\n" +
	"\x05media\x18\v \x03(\v2\x15.thread.MediaResponseR\x05media\x12,\n" +
	"\x12mentioned_user_ids\x18\f \x03(\tR\x10mentionedUserIds\"\x8e\x01\n" +
	"\x0fThreadsResponse\x120\n" +
	"\athreads\x18\x01 \x03(\v2\x16.thread.ThreadResponseR\athreads\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x8d\x01\n" +
	"\x0fRepliesResponse\x12/\n" +
	"\areplies\x18\x01 \x03(\v2\x15.thread.ReplyResponseR\areplies\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xc1\x01\n" +
	"\x11CreatePollRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\x12\x18\n" +
	"\aoptions\x18\x03 \x03(\tR\aoptions\x127\n" +
	"\tcloses_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bclosesAt\x12 \n" +
	"\fwho_can_vote\x18\x05 \x01(\tR\n" +
	"whoCanVote2\x9e\v\n" +
	"\rThreadService\x12E\n" +
	"\fCreateThread\x12\x1b.thread.CreateThreadRequest\x1a\x16.thread.ThreadResponse\"\x00\x12C\n" +
	"\rGetThreadById\x12\x18.thread.GetThreadRequest\x1a\x16.thread.ThreadResponse\"\x00\x12N\n" +
	"\x10GetThreadsByUser\x12\x1f.thread.GetThreadsByUserRequest\x1a\x17.thread.ThreadsResponse\"\x00\x12E\n" +
	"\fUpdateThread\x12\x1b.thread.UpdateThreadRequest\x1a\x16.thread.ThreadResponse\"\x00\x12E\n" +
	"\fDeleteThread\x12\x1b.thread.DeleteThreadRequest\x1a\x16.google.protobuf.Empty\"\x00\x12B\n" +
	"\vCreateReply\x12\x1a.thread.CreateReplyRequest\x1a\x15.thread.ReplyResponse\"\x00\x12R\n" +
	"\x12GetRepliesByThread\x12!.thread.GetRepliesByThreadRequest\x1a\x17.thread.RepliesResponse\"\x00\x12B\n" +
	"\vUpdateReply\x12\x1a.thread.UpdateReplyRequest\x1a\x15.thread.ReplyResponse\"\x00\x12C\n" +
	"\vDeleteReply\x12\x1a.thread.DeleteReplyRequest\x1a\x16.google.protobuf.Empty\"\x00\x12A\n" +
	"\n" +
	"LikeThread\x12\x19.thread.LikeThreadRequest\x1a\x16.google.protobuf.Empty\"\x00\x12E\n" +
	"\fUnlikeThread\x12\x1b.thread.UnlikeThreadRequest\x1a\x16.google.protobuf.Empty\"\x00\x12?\n" +
	"\tLikeReply\x12\x18.thread.LikeReplyRequest\x1a\x16.google.protobuf.Empty\"\x00\x12C\n" +
	"\vUnlikeReply\x12\x1a.thread.UnlikeReplyRequest\x1a\x16.google.protobuf.Empty\"\x00\x12E\n" +
	"\fRepostThread\x12\x1b.thread.RepostThreadRequest\x1a\x16.google.protobuf.Empty\"\x00\x12E\n" +
	"\fRemoveRepost\x12\x1b.thread.RemoveRepostRequest\x1a\x16.google.protobuf.Empty\"\x00\x12I\n" +
	"\x0eBookmarkThread\x12\x1d.thread.BookmarkThreadRequest\x1a\x16.google.protobuf.Empty\"\x00\x12I\n" +
	"\x0eRemoveBookmark\x12\x1d.thread.RemoveBookmarkRequest\x1a\x16.google.protobuf.Empty\"\x00\x12?\n" +
	"\n" +
	"CreatePoll\x12\x19.thread.CreatePollRequest\x1a\x14.thread.PollResponse\"\x00\x12=\n" +
	"\bVotePoll\x12\x17.thread.VotePollRequest\x1a\x16.google.protobuf.Empty\"\x00\x12N\n" +
	"\x0eGetPollResults\x12\x1d.thread.GetPollResultsRequest\x1a\x1b.thread.PollResultsResponse\"\x00B\x16Z\x14thread-service/protob\x06proto3"

var (
	file_proto_thread_proto_rawDescOnce sync.Once
	file_proto_thread_proto_rawDescData []byte
)

func file_proto_thread_proto_rawDescGZIP() []byte {
	file_proto_thread_proto_rawDescOnce.Do(func() {
		file_proto_thread_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_thread_proto_rawDesc), len(file_proto_thread_proto_rawDesc)))
	})
	return file_proto_thread_proto_rawDescData
}

var file_proto_thread_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_proto_thread_proto_goTypes = []any{
	(*MediaInfo)(nil),                 // 0: thread.MediaInfo
	(*CreateThreadRequest)(nil),       // 1: thread.CreateThreadRequest
	(*PollInfo)(nil),                  // 2: thread.PollInfo
	(*GetThreadRequest)(nil),          // 3: thread.GetThreadRequest
	(*GetThreadsByUserRequest)(nil),   // 4: thread.GetThreadsByUserRequest
	(*UpdateThreadRequest)(nil),       // 5: thread.UpdateThreadRequest
	(*DeleteThreadRequest)(nil),       // 6: thread.DeleteThreadRequest
	(*CreateReplyRequest)(nil),        // 7: thread.CreateReplyRequest
	(*GetRepliesByThreadRequest)(nil), // 8: thread.GetRepliesByThreadRequest
	(*UpdateReplyRequest)(nil),        // 9: thread.UpdateReplyRequest
	(*DeleteReplyRequest)(nil),        // 10: thread.DeleteReplyRequest
	(*LikeThreadRequest)(nil),         // 11: thread.LikeThreadRequest
	(*UnlikeThreadRequest)(nil),       // 12: thread.UnlikeThreadRequest
	(*LikeReplyRequest)(nil),          // 13: thread.LikeReplyRequest
	(*UnlikeReplyRequest)(nil),        // 14: thread.UnlikeReplyRequest
	(*RepostThreadRequest)(nil),       // 15: thread.RepostThreadRequest
	(*RemoveRepostRequest)(nil),       // 16: thread.RemoveRepostRequest
	(*BookmarkThreadRequest)(nil),     // 17: thread.BookmarkThreadRequest
	(*RemoveBookmarkRequest)(nil),     // 18: thread.RemoveBookmarkRequest
	(*VotePollRequest)(nil),           // 19: thread.VotePollRequest
	(*GetPollResultsRequest)(nil),     // 20: thread.GetPollResultsRequest
	(*ThreadResponse)(nil),            // 21: thread.ThreadResponse
	(*MediaResponse)(nil),             // 22: thread.MediaResponse
	(*PollResponse)(nil),              // 23: thread.PollResponse
	(*PollOptionResponse)(nil),        // 24: thread.PollOptionResponse
	(*PollResultsResponse)(nil),       // 25: thread.PollResultsResponse
	(*ReplyResponse)(nil),             // 26: thread.ReplyResponse
	(*ThreadsResponse)(nil),           // 27: thread.ThreadsResponse
	(*RepliesResponse)(nil),           // 28: thread.RepliesResponse
	(*CreatePollRequest)(nil),         // 29: thread.CreatePollRequest
	(*timestamppb.Timestamp)(nil),     // 30: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 31: google.protobuf.Empty
}
var file_proto_thread_proto_depIdxs = []int32{
	0,  // 0: thread.CreateThreadRequest.media:type_name -> thread.MediaInfo
	30, // 1: thread.CreateThreadRequest.scheduled_at:type_name -> google.protobuf.Timestamp
	2,  // 2: thread.CreateThreadRequest.poll:type_name -> thread.PollInfo
	30, // 3: thread.PollInfo.closes_at:type_name -> google.protobuf.Timestamp
	0,  // 4: thread.CreateReplyRequest.media:type_name -> thread.MediaInfo
	30, // 5: thread.ThreadResponse.scheduled_at:type_name -> google.protobuf.Timestamp
	30, // 6: thread.ThreadResponse.created_at:type_name -> google.protobuf.Timestamp
	30, // 7: thread.ThreadResponse.updated_at:type_name -> google.protobuf.Timestamp
	22, // 8: thread.ThreadResponse.media:type_name -> thread.MediaResponse
	23, // 9: thread.ThreadResponse.poll:type_name -> thread.PollResponse
	30, // 10: thread.PollResponse.closes_at:type_name -> google.protobuf.Timestamp
	24, // 11: thread.PollResponse.options:type_name -> thread.PollOptionResponse
	24, // 12: thread.PollResultsResponse.options:type_name -> thread.PollOptionResponse
	30, // 13: thread.ReplyResponse.created_at:type_name -> google.protobuf.Timestamp
	30, // 14: thread.ReplyResponse.updated_at:type_name -> google.protobuf.Timestamp
	22, // 15: thread.ReplyResponse.media:type_name -> thread.MediaResponse
	21, // 16: thread.ThreadsResponse.threads:type_name -> thread.ThreadResponse
	26, // 17: thread.RepliesResponse.replies:type_name -> thread.ReplyResponse
	30, // 18: thread.CreatePollRequest.closes_at:type_name -> google.protobuf.Timestamp
	1,  // 19: thread.ThreadService.CreateThread:input_type -> thread.CreateThreadRequest
	3,  // 20: thread.ThreadService.GetThreadById:input_type -> thread.GetThreadRequest
	4,  // 21: thread.ThreadService.GetThreadsByUser:input_type -> thread.GetThreadsByUserRequest
	5,  // 22: thread.ThreadService.UpdateThread:input_type -> thread.UpdateThreadRequest
	6,  // 23: thread.ThreadService.DeleteThread:input_type -> thread.DeleteThreadRequest
	7,  // 24: thread.ThreadService.CreateReply:input_type -> thread.CreateReplyRequest
	8,  // 25: thread.ThreadService.GetRepliesByThread:input_type -> thread.GetRepliesByThreadRequest
	9,  // 26: thread.ThreadService.UpdateReply:input_type -> thread.UpdateReplyRequest
	10, // 27: thread.ThreadService.DeleteReply:input_type -> thread.DeleteReplyRequest
	11, // 28: thread.ThreadService.LikeThread:input_type -> thread.LikeThreadRequest
	12, // 29: thread.ThreadService.UnlikeThread:input_type -> thread.UnlikeThreadRequest
	13, // 30: thread.ThreadService.LikeReply:input_type -> thread.LikeReplyRequest
	14, // 31: thread.ThreadService.UnlikeReply:input_type -> thread.UnlikeReplyRequest
	15, // 32: thread.ThreadService.RepostThread:input_type -> thread.RepostThreadRequest
	16, // 33: thread.ThreadService.RemoveRepost:input_type -> thread.RemoveRepostRequest
	17, // 34: thread.ThreadService.BookmarkThread:input_type -> thread.BookmarkThreadRequest
	18, // 35: thread.ThreadService.RemoveBookmark:input_type -> thread.RemoveBookmarkRequest
	29, // 36: thread.ThreadService.CreatePoll:input_type -> thread.CreatePollRequest
	19, // 37: thread.ThreadService.VotePoll:input_type -> thread.VotePollRequest
	20, // 38: thread.ThreadService.GetPollResults:input_type -> thread.GetPollResultsRequest
	21, // 39: thread.ThreadService.CreateThread:output_type -> thread.ThreadResponse
	21, // 40: thread.ThreadService.GetThreadById:output_type -> thread.ThreadResponse
	27, // 41: thread.ThreadService.GetThreadsByUser:output_type -> thread.ThreadsResponse
	21, // 42: thread.ThreadService.UpdateThread:output_type -> thread.ThreadResponse
	31, // 43: thread.ThreadService.DeleteThread:output_type -> google.protobuf.Empty
	26, // 44: thread.ThreadService.CreateReply:output_type -> thread.ReplyResponse
	28, // 45: thread.ThreadService.GetRepliesByThread:output_type -> thread.RepliesResponse
	26, // 46: thread.ThreadService.UpdateReply:output_type -> thread.ReplyResponse
	31, // 47: thread.ThreadService.DeleteReply:output_type -> google.protobuf.Empty
	31, // 48: thread.ThreadService.LikeThread:output_type -> google.protobuf.Empty
	31, // 49: thread.ThreadService.UnlikeThread:output_type -> google.protobuf.Empty
	31, // 50: thread.ThreadService.LikeReply:output_type -> google.protobuf.Empty
	31, // 51: thread.ThreadService.UnlikeReply:output_type -> google.protobuf.Empty
	31, // 52: thread.ThreadService.RepostThread:output_type -> google.protobuf.Empty
	31, // 53: thread.ThreadService.RemoveRepost:output_type -> google.protobuf.Empty
	31, // 54: thread.ThreadService.BookmarkThread:output_type -> google.protobuf.Empty
	31, // 55: thread.ThreadService.RemoveBookmark:output_type -> google.protobuf.Empty
	23, // 56: thread.ThreadService.CreatePoll:output_type -> thread.PollResponse
	31, // 57: thread.ThreadService.VotePoll:output_type -> google.protobuf.Empty
	25, // 58: thread.ThreadService.GetPollResults:output_type -> thread.PollResultsResponse
	39, // [39:59] is the sub-list for method output_type
	19, // [19:39] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_proto_thread_proto_init() }
func file_proto_thread_proto_init() {
	if File_proto_thread_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_thread_proto_rawDesc), len(file_proto_thread_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_thread_proto_goTypes,
		DependencyIndexes: file_proto_thread_proto_depIdxs,
		MessageInfos:      file_proto_thread_proto_msgTypes,
	}.Build()
	File_proto_thread_proto = out.File
	file_proto_thread_proto_goTypes = nil
	file_proto_thread_proto_depIdxs = nil
}
