root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -mod=mod -o ./tmp/main ."
bin = "./tmp/main"
delay = 1000
exclude_dir = ["assets", "tmp", "vendor"]
include_ext = ["go", "tpl", "tmpl", "html"]
kill_delay = "0s"
log = "build-errors.log"
stop_on_error = true

[screen]
clear_on_rebuild = true 